HW02 - Add Array10toSquaredArray app
Serge-prospect/SergeyKuzhalQAAuto pull request #2
Opened 2022-02-23 21:40 UTC by Serge-prospect

Please review HW02 - Array10toSquaredArray.

2022-02-23 23:24 UTC, EgorAntonovich requested changes

2022-02-23 23:24 UTC, EgorAntonovich commented on Array10toSquaredArray/Array10toSquaredArray/Program.cs
> +        {
Why you create 2 arrays?
Based on issue we should create 1 array and fill him by squared indexes. Seems like it can be solved by 1 array.

2022-03-08 11:17 UTC, Serge-prospect commented on Array10toSquaredArray/Array10toSquaredArray/Program.cs
> +        {
Please review changes: 'Update to 1 squared index array'

2022-03-09 22:17 UTC, EgorAntonovich approved these changes
Merge PR

2022-03-16 07:50 UTC, merged