Display info of 5 books
Serge-prospect/SergeyKuzhalQAAuto pull request #5
Opened 2022-03-23 01:30 UTC by Serge-prospect

Please review HW05 - BooksInfo.

2022-03-30 16:18 UTC, EgorAntonovich requested changes

2022-03-30 16:18 UTC, EgorAntonovich commented on BooksInfo/BooksInfo/Program.cs
> +                library[index] = new Book(id);
you can set id to `new Book()` like this new Book((index + 1).To String()) if you want.  but better create custom objects for fill array and set info in each property without default values.

2022-03-30 16:18 UTC, EgorAntonovich commented on BooksInfo/BooksInfo/Book.cs
> +            Console.WriteLine($"ID: {Id}     Title: {Title}     Pages: {Pages}");
you can use \t instead of million spaces

2022-03-31 16:20 UTC, Serge-prospect commented on BooksInfo/BooksInfo/Program.cs
> +                library[index] = new Book(id);
If I simply add objects with **id**, **title**, **pages**, how can I make sure that **id** value is unique? When I create a **Book** object with **id** (no set) field only in it via adding +1 in **id** in cycle, it is realy unique. Then I fill in other fields of the created **Book** objects by any data as I want.

2022-04-01 10:32 UTC, Serge-prospect commented on BooksInfo/BooksInfo/Program.cs
> +                library[index] = new Book(id);
Changed to another way of getting a unique ID.

2022-04-12 19:21 UTC, EgorAntonovich approved these changes

2022-04-17 21:51 UTC, merged