HW07 - Add Office app
Serge-prospect/SergeyKuzhalQAAuto pull request #7
Opened 2022-04-03 23:13 UTC by Serge-prospect

Please review 'HW07 - Add Office app'.

2022-04-12 19:30 UTC, EgorAntonovich approved these changes

2022-04-12 19:31 UTC, EgorAntonovich requested changes

2022-04-12 19:31 UTC, EgorAntonovich commented on Office/Office/Program.cs
> +            foreach (Employee currentEmployee in officeEmployees)
Simplify 3 foreachs into 1 please

2022-04-17 21:55 UTC, Serge-prospect commented on Office/Office/Program.cs
> +            foreach (Employee currentEmployee in officeEmployees)
HW07 - updated 3 foreaches  to single method.

2022-04-20 09:32 UTC, EgorAntonovich approved these changes

2022-04-20 09:32 UTC, merged